// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2ClEd8W8KGo09go1WiW1VKeJdwN794c',
    appId: '1:749711652593:web:a5a47f42cbc0fd04599b50',
    messagingSenderId: '749711652593',
    projectId: 'mappage-4c2af',
    authDomain: 'mappage-4c2af.firebaseapp.com',
    storageBucket: 'mappage-4c2af.appspot.com',
    measurementId: 'G-DTBMF0EXM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqowAvmsu9AulT4bYOgDnqlNZj3oZYGI',
    appId: '1:749711652593:android:29c67051e5538de7599b50',
    messagingSenderId: '749711652593',
    projectId: 'mappage-4c2af',
    storageBucket: 'mappage-4c2af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQThi79UuI7SWh-J_Qaw7qv6bC7zGF80',
    appId: '1:749711652593:ios:6756c245bd45ed24599b50',
    messagingSenderId: '749711652593',
    projectId: 'mappage-4c2af',
    storageBucket: 'mappage-4c2af.appspot.com',
    iosClientId: '749711652593-ol3dcrap718p9so32ovi400v26o3o6a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYQThi79UuI7SWh-J_Qaw7qv6bC7zGF80',
    appId: '1:749711652593:ios:6756c245bd45ed24599b50',
    messagingSenderId: '749711652593',
    projectId: 'mappage-4c2af',
    storageBucket: 'mappage-4c2af.appspot.com',
    iosClientId: '749711652593-ol3dcrap718p9so32ovi400v26o3o6a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
